[package]
name = "ytfilter"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
quick-xml = { version = "0.38.1", features = ["serialize"] }
reqwest = { version = "0.12.22", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-aux = "4.7.0"
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
tempfile = "3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
